services:
  postgres:
    image: postgres:15
    container_name: codearena-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: codearena_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - codearena-network

volumes:
  postgres_data:

networks:
  codearena-network:
    driver: bridge
